[package]
name = "wrapper"
version = "0.1.0"
authors = ["Matt Garnett <matt.garnett@me.com>"]
edition = "2018"

[dependencies]
arrayref = "0.3.5"
interface = { path = "../interface", features = ["generate"] }

proof = { path = "../proof", features = ["generate"] }

[dev-dependencies]
oof = "0.1.1"
